services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: kad
      POSTGRES_PASSWORD: kad
      POSTGRES_DB: kad
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata:
